### ISSUE TITLE
java.lang.NumberFormatException: For input string: "0dac1945-c1c6-4dec-b175-b5871d153da7"

### ISSUE THREAD

**Issue by quxiaojing** [alibaba/SmartEngine#86]
ExecutionInstanceEntity executionInstanceEntity = new ExecutionInstanceEntity();
 executionInstanceEntity.setId(Long.valueOf(executionInstance.getInstanceId()));

java.lang.NumberFormatException: For input string: "0dac1945-c1c6-4dec-b175-b5871d153da7"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.alibaba.smart.framework.engine.persister.database.service.RelationshipDatabaseExecutionInstanceStorage.buildExecutionInstanceEntity(RelationshipDatabaseExecutionInstanceStorage.java:49)

**Comment by vavi** [comment]
你的idGenernator 要修改下，返回long类型。 或者你把表结构改成char类型。

**Comment by quxiaojing** [comment]
只能改idGenernator，底层很多地方都是parseLong之后保存的，改表结构就要改框架代码了
